services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "habrdb"
            POSTGRES_USER: "habrpguser"
            POSTGRES_PASSWORD: "pgpwd4habr"
        ports:
        - "5432:5432"
    pgadmin4:
        image: elestio/pgadmin:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@trackme.local
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 8080
        ports:
        - "172.17.0.1:8080:8080"
        volumes:
        - ./servers.json:/pgadmin4/servers.json
    rabbitmq:
        image: rabbitmq:latest
        container_name: trackme_rebbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: trackme
            RABBITMQ_DEFAULT_PASS: trackme_pass
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    postgres_data: