spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service

server:
  port: 8081